spring.datasource.url=jdbc:postgresql://ep-icy-shadow-ae64rqv3-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zDsxr9Tu0QBL

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=dailycore-dev-secret-key-change-in-production-32chars
app.jwt.expiration-ms=86400000